function createaxes(Parent1, YMatrix1)
%CREATEAXES(PARENT1, YMATRIX1)
%  PARENT1:  axes parent
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 11-May-2017 14:57:53

% Create axes
axes1 = axes('Parent',Parent1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot(YMatrix1,'Parent',axes1);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 100]);
% Set the remaining axes properties
set(axes1,'XTick',...
    [0 4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92 96],...
    'XTickLabel',...
    {'0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24'});

